name: ESLint

on:
  push:
    branches:
      - main
      - '**/feature/**'
      - dev
  pull_request:
    branches:
      - dev
    paths:
      - 'frontend/**'

jobs:
  lint:
    name: Run ESLint and generate SARIF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run ESLint and generate SARIF
        working-directory: frontend
        run: |
          npm install --save-dev @microsoft/eslint-formatter-sarif
          npx eslint . \
            --config eslint.config.mjs \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif

      - name: Upload SARIF file to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: frontend/eslint-results.sarif
